[build]
  publish = "build/"
  command = "pnpm run build"
  environment = { NODE_VERSION = "18.12.0" }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    Access-Control-Allow-Origin = "*"
